[package]
name = "sqlite-adapter"
version = "0.1.0"
edition.workspace = true

[dependencies]
domain = { path = "../../domain" }
rusqlite = { version = "0.31", features = ["bundled", "functions", "chrono"] }

[dev-dependencies]
tempfile = "3"
